# Build and deploy stateless images to Google Cloud Run as serverless applications.
# Repo: https://github.com/CircleCI-Public/gcp-cloud-run-orb
# Home: https://cloud.google.com/run/

version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2
jobs:
  build_and_deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: "gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}"
      - cloudrun/deploy:
          image: "gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}"
          platform: managed
          region: ${REGION}
          service-name: ${SERVICE_NAME}
          unauthenticated: true
workflows:
  build_and_deploy_to_managed_workflow:
    jobs:
      - build_and_deploy
